### ISSUE TITLE
Enable and ensure off-line support is working

### ISSUE THREAD

**Issue by pld** [onaio/enketo-express#1]

**Comment by geoffreymuchai** [comment]
Reference:
https://github.com/onaio/enketo-express/blob/master/APIv2.md

**Comment by ivermac** [comment]
![screen shot 2015-03-18 at 5 17 46 pm](https://cloud.githubusercontent.com/assets/1128227/6710562/a613c1ca-cd92-11e4-806c-133a2c145f89.png)

Enabling of offline support in enketo express creates an IndexedDB on the browser called 'enketo' with stores the submissions when you a user is offline. This submissions can be uploaded by clicking the 'Upload' button, as seen in the screenshot above, or uploaded automatically as suggested above which I haven't tested but I plan to do so on stage. The offline url can be generated by the following command if you are using httpie:
```
http -a <api-token>: "http://localhost:8005/api/v2/survey/offline?server_url=http://localhost:8000/<username>&form_id=<id_string>"
```
If you are using curl you can use the following command:
```
curl --user 0nad1srupts: "http://localhost:8005/api/v2/survey/offline?server_url=http://localhost:8000/ivermac&form_id=enketo_express_offline"
```

The output is a json response that contains `code` which is the status code and `offline_url` which is the offline url :-).  I created a simple form with 4 fields of types select_one, geopoint, photo and audio and I was able make a successful upload which I could see on the /data endpoint though I couldn't see the photo and audio I uploaded on the /media endpoint, but may be it's because of my settings; I will test this on the stage server too. @pld, @uk and @geoffreymuchai would it make sense to create a form with all the types(geolopoint, select_one e.t.c) we support and test if all of them work? These are my findings so far and I welcome questions and suggestions as I continue doing research. The next step i'm taking is to test it on stage

**Comment by pld** [comment]
This is great, and yes it makes sense to use a test-form covering all the different types of questions.

**Comment by ukanga** [comment]
This also does indicate we may need to expose the offline url in the api, how different are the urls?

**Comment by ivermac** [comment]
From the test xls form that I used, the command above generated the following offline url:
```
http://localhost:8005/_/#YYYo
```
removing the `/offline` from the command above which is for an online survey generates the following url:
```
http://localhost:8005/::YYYo
```
But this is just for one form and might not be conclusive

**Comment by geoffreymuchai** [comment]
The offline url can be retrieved by making a call from Ona to
enketo-express on the `/api_v2/survey/offline` endpoint

Reference:
https://github.com/enketo/enketo-express/blob/master/APIv2.md#survey-endpoint

**Comment by ivermac** [comment]
Did another round of tests with a different form with different data types including an audio and photo data type. Again, I noticed that the media files (photo and audio) were not uploading. I have asked on the enketo mailing group (topic: [Offline Media Upload] (https://groups.google.com/forum/#!forum/enketo-users)) if this functionality is available for offline forms and I hope I will get a response. So far all the other datatypes seem to work fine

**Comment by mberg** [comment]
Not sure full offline support works yet with enketo express

**Comment by pld** [comment]
@mberg is having this working a prerequisite for using our version of
enketo in production?

**Comment by mberg** [comment]
I don't see attachments as a requirement.  I think support is coming for
that soon.  Can we confirm the rest of the

Other option is we use enketo for regular forms and express for edits but
that would be a pain i realize

**Comment by pld** [comment]
OK cool, @ivermac go ahead and create an issue for enabling attachments in
offline forms (to work on later, not now). If everything else is working I
think this issue is closed then.
