### ISSUE TITLE
Research Enketo authentication issues

### ISSUE THREAD

**Issue by pld** [onaio/enketo-express#18]
* [x] research allowing enketo to fall back to another authentication method if JWT link is not provided or incorrect
* [x] research remove JWT from the final URL where the enketo form is loaded
* [x] research maintain session once user logins or is redirected from authentication, no need to pass JWT in url for each request.

**Comment by ivermac** [comment]
The research results are out:
@pld @ukanga @rowo @mberg  @smusula Enketo (literally it's core that falls back since it's the default authenticator) can fallback to another authentication method - zebra's login page - if the default authentication fails. That solves **1st** checkbox issue. On successful authentication we set the enketo cookies and redirect the user to the enketo url. The cookies are used for subsequent requests between core and enketo which I believe solves the **3rd** checkbox issue above.We thought it best with @royrutto that these cookies are also set during normal authentication - when a user logs in to use zebra -  so that the user does not have to re-authenticate when he/she tries to access the enketo webform that has been shared with him/her. In short, once you are authenticated with zebra, you can access the enketo urls (yours and the ones shared with you), solving the **2nd** problem. The changes I did were mainly in core and zebra and none in enketo.

**Comment by rowo** [comment]
How long would these solutions take to do, roughly?

**Comment by ivermac** [comment]
I would give it a day

**Comment by pld** [comment]
Cool, so the conclusion is that this is now an implementation issue, @ivermac will open zebra and core PRs to handle this, will be tracked here, https://github.com/onaio/zebra/issues/3617, https://github.com/onaio/zebra/issues/3550, closing this
